### replies 리스트 조회
GET {{local_api}}/api/replies/kr/Jazion.T

### replies 생성
POST {{local_api}}/api/replies
Content-Type: application/json

{
    "toon": "Jazion.T",
    "area": "kr",
    "nickname": "고수",
    "content": "우와",
    "password": "1234"
}

> {%
    client.global.set('id', response.body.id)
    client.log(client.global.get('id'));
%}

### replies 삭제
POST {{local_api}}/api/replies/{{id}}
Content-Type: application/json

{
    "password": "1234"
}